export default {
  input: "index.js",
  external: ["acorn"],
  output: {
    file: "index.cjs",
    exports: 'default',
    format: "cjs",
    banner: "// DO NOT edit this file, it's auto-generated from 'rollup.config.js'; any changes will be overwritten. \n"
  }
};
