import path from "path";
import { rollup } from "rollup";

const PATH_ROOT = path.resolve(import.meta.dirname, "../");

let inputOptions = {
    input: path.resolve(PATH_ROOT, "index.js"),
    external: ["acorn"]
}

let outputOptions = {
    output: {
        file: path.resolve(PATH_ROOT, "index.cjs"),
        format: "cjs",
        banner: "// DO NOT edit this file, it's auto-generated from 'constructor/build.js'; any changes will be overwritten. \n"
    }
}

rollup(inputOptions).then(bundle => bundle.write(outputOptions));
